name: pantheon-upstream
recipe: drupal9
proxy:
  mailhog:
    - mailhog.pantheon-upstream.lndo.site
  phpmyadmin:
    - phpmyadmin.pantheon-upstream.lndo.site
services:
  appserver:
    type: php:8.0
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  elasticsearch:
    type: elasticsearch:7
    portforward: 9200
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
config:
  webroot: web
